from __future__ import annotations

import json
import logging
import tempfile
from pathlib import Path

from .cloudinary_client import upload_cover
from .config import Settings
from .database import PostRepository
from .image_generator import AllImageProvidersFailed, generate_cover_image
from .llm import FallbackLLM
from .models import PublishResult
from .notifications import maybe_send_daily_summary
from .research import discover_search_candidates, research_topic
from .trends import collect_trends
from .writer import generate_article, manual_topic, select_topic

LOGGER = logging.getLogger(__name__)



def _limit_result(settings: Settings, language: str, count: int) -> dict:
    payload = {
        "status": "daily-limit",
        "language": language,
        "published_today": count,
        "daily_limit": settings.daily_post_limit_per_language,
        "timezone": settings.publish_timezone,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return payload


def run_agent(
    settings: Settings,
    *,
    topic_override: str | None = None,
    language: str = "ur",
    dry_run: bool = False,
    skip_image: bool = False,
) -> dict:
    if language not in {"ur", "en"}:
        raise ValueError("language must be 'ur' or 'en'")

    missing = settings.validate_for_run(publish=not dry_run, generate_image=not skip_image)
    if missing:
        raise RuntimeError(f"Missing required environment variables: {settings.pretty_missing(missing)}")

    repo = None if dry_run else PostRepository(settings)
    if repo:
        today_count = repo.count_today_agent_posts(language)
        if today_count >= settings.daily_post_limit_per_language:
            LOGGER.info(
                "Daily %s limit reached: %d/%d (%s)",
                language,
                today_count,
                settings.daily_post_limit_per_language,
                settings.publish_timezone,
            )
            return _limit_result(settings, language, today_count)

    llm = FallbackLLM(settings)

    if topic_override:
        selection = manual_topic(topic_override, language=language)
    else:
        trends = collect_trends(settings)

        if repo:
            excluded = repo.today_source_topics() | repo.recent_source_topics(language)
            before = len(trends)
            trends = [row for row in trends if row.query.strip().casefold() not in excluded]
            LOGGER.info("Topic dedupe: %d -> %d candidates for language=%s", before, len(trends), language)
            if not trends:
                fallback = discover_search_candidates(settings)
                trends = [row for row in fallback if row.query.strip().casefold() not in excluded]

        # select_topic binds the article idea to an exact candidate index.
        # Do not fuzzy-repair source_query afterward; that can attach an unrelated trend.
        selection = select_topic(llm, trends, settings, language=language)

    LOGGER.info(
        "Selected topic: %s | source=%s | source_provider=%s | language=%s | relevance=%s | selector=%s",
        selection.topic,
        selection.source_query,
        selection.source_provider,
        language,
        selection.relevance_score,
        selection.provider,
    )

    if repo:
        if selection.source_query.casefold() in repo.today_source_topics():
            LOGGER.warning("Skipping source topic already used today: %s", selection.source_query)
            payload = {"status": "duplicate-today", "topic": selection.source_query, "language": language}
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return payload

        duplicate = repo.find_recent_topic(selection.source_query, language)
        if duplicate:
            LOGGER.warning(
                "Skipping duplicate %s topic published in last %d days: %s (%s)",
                language,
                settings.duplicate_window_days,
                duplicate.get("title"),
                duplicate.get("slug"),
            )
            payload = {
                "status": "duplicate",
                "topic": selection.source_query,
                "language": language,
                "post": duplicate,
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return payload

    research = research_topic(settings, selection)
    LOGGER.info("Research context ready via %s", research.provider)

    article = generate_article(llm, selection, language=language, research=research)
    LOGGER.info(
        "Article generated by %s: %s (%d words, language=%s)",
        article.provider,
        article.title,
        article.word_count,
        article.language,
    )

    with tempfile.TemporaryDirectory(prefix="km-afaq-agent-") as tmp:
        cover = None
        if not skip_image:
            try:
                cover = generate_cover_image(settings, article.image_prompt, Path(tmp) / "cover")
            except AllImageProvidersFailed:
                if not settings.allow_publish_without_image:
                    raise
                LOGGER.exception("All cover-image providers failed; ALLOW_PUBLISH_WITHOUT_IMAGE=true so pipeline continues")

        if dry_run:
            preview = {
                "status": "dry-run",
                "language": language,
                "topic": selection.source_query,
                "topic_angle": selection.angle,
                "topic_category": selection.topic_category,
                "source_provider": selection.source_provider,
                "research_provider": research.provider,
                "article": {
                    "title": article.title,
                    "slug": article.slug,
                    "excerpt": article.excerpt,
                    "seo_description": article.seo_description,
                    "word_count": article.word_count,
                    "provider": article.provider,
                    "language": article.language,
                    "image_prompt": article.image_prompt,
                },
                "image_ready": bool(cover),
                "image_provider": cover.provider if cover else None,
            }
            print(json.dumps(preview, ensure_ascii=False, indent=2))
            return preview

        media = upload_cover(settings, cover.path) if cover else None
        LOGGER.info("Cloudinary upload complete: %s", media.public_id if media else "no image")

        assert repo is not None
        result: PublishResult = repo.publish(
            article,
            selection,
            media,
            cover,
            research_provider=research.provider,
        )
        LOGGER.info("Supabase publish complete: %s", result.url)

        # No per-post notification. Only the 10/10 completion summary is sent once.
        daily_summary = maybe_send_daily_summary(settings, repo)

        summary = {
            "status": "published",
            "post_id": result.post_id,
            "title": result.title,
            "url": result.url,
            "language": language,
            "topic": selection.source_query,
            "topic_category": selection.topic_category,
            "source_provider": selection.source_provider,
            "research_provider": research.provider,
            "article_provider": article.provider,
            "image_provider": cover.provider if cover else None,
            "image_source_url": cover.source_url if cover else None,
            "cloudinary_public_id": media.public_id if media else None,
            "cloudinary_asset_id": media.asset_id if media else None,
            "daily_line_summary": daily_summary,
        }
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return summary
